name: cascade_flow_workspace
packages:
  - .
  - app/**
  - packages/**
  - features/**

command:
  bootstrap:
    runPubGetInParallel: true
    usePubspecOverrides: true

scripts:
  analyze:
    description: Run static analysis across the workspace.
    run: melos exec -c 1 -- flutter analyze
  test:
    description: Run Flutter tests at the app level.
    run: melos exec -c 1 -- flutter test
