name: cascade_flow
description: "CascadeFlow productivity companion app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cascade_flow_core:
    path: packages/core
  cascade_flow_data:
    path: packages/data
  cascade_flow_infrastructure:
    path: packages/infrastructure
  cascade_flow_presentation:
    path: packages/presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  melos: ^7.1.1

flutter:
  uses-material-design: true

melos:
  command:
    bootstrap:
      runPubGetInParallel: true
      usePubspecOverrides: true

  packages:
    - app/**
    - core/**
    - infrastructure/**
    - features/**
    - packages/**

  scripts:
    analyze:
      description: Run static analysis across the workspace.
      run: dart run melos:melos exec -c 1 -- flutter analyze
    test:
      description: Run Flutter tests at the app level.
      run: dart run melos:melos exec -c 1 -- flutter test
