name: cascade_flow_prioritize
description: Prioritize feature slice (domain, data, presentation).
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.19.0'

resolution: workspace

dependencies:
  cascade_flow_core:
    path: ../../packages/core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
