name: cascade_flow_app
description: Flutter runner for CascadeFlow.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.29.0'

resolution: workspace

dependencies:
  cascade_flow_core:
    path: ../packages/core
  cascade_flow_data:
    path: ../packages/data
  cascade_flow_infrastructure:
    path: ../packages/infrastructure
  cascade_flow_presentation:
    path: ../packages/presentation
  cascade_flow_ingest:
    path: ../features/ingest
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
