name: cascade_flow_app
description: Flutter runner for CascadeFlow.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.29.0'

resolution: workspace

dependencies:
  cascade_flow_core:
    path: ../packages/core
  cascade_flow_data:
    path: ../packages/data
  cascade_flow_infrastructure:
    path: ../packages/infrastructure
  cascade_flow_ingest:
    path: ../features/ingest
  cascade_flow_presentation:
    path: ../packages/presentation
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.4
  riverpod: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce: ^2.14.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
