name: cascade_flow_infrastructure
description: Cross-cutting services and platform integrations for CascadeFlow.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dependencies:
  cascade_flow_core:
    path: ../core
  cascade_flow_data:
    path: ../data
  cascade_flow_ingest:
    path: ../../features/ingest
  collection: ^1.18.0
  flutter_secure_storage: ^9.2.2
  hive_ce: ^2.14.0
  hive_ce_flutter: ^2.3.2
  meta: ^1.11.0
  path_provider: ^2.1.5
  riverpod: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  test: ^1.24.2
  very_good_analysis: ^10.0.0
