name: cascade_flow_infrastructure
description: Cross-cutting services and platform integrations for CascadeFlow.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dependencies:
  cascade_flow_core:
    path: ../core
  cascade_flow_data:
    path: ../data
  collection: ^1.18.0
  hive_ce: ^2.14.0
  hive_ce_flutter: ^2.3.2
  meta: ^1.11.0
  path_provider: ^2.1.5
  riverpod: ^3.0.1

dev_dependencies:
  test: ^1.24.2
  very_good_analysis: ^10.0.0
