name: cascade_flow_core
description: Core primitives and value objects shared across CascadeFlow.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies: {}

dev_dependencies:
  very_good_analysis: ^10.0.0
