name: cascade_flow_core
description: Core primitives and value objects shared across CascadeFlow.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^10.0.0
